### ISSUE TITLE
Undefined array key 'lists'

### ISSUE THREAD

**Issue by fluchtkapsel** [kuenzign/WikiMarkdown#19]
```
PHP Warning:  Undefined array key "lists" in […]/extensions/WikiMarkdown/includes/WikiMarkdown.php on line 109; PHP message: PHP Warning:  Trying to access array offset on null in […]/extensions/WikiMarkdown/includes/WikiMarkdown.php on line 109; […]
```
I guess that's because the extension was written with ParsedownExtenden <1.2 in mind.

**Comment by kuenzign** [comment]
Yes, downgrade ParsedownExtended to version 1.1.2 and this should be resolved.

**Comment by lattaai9** [comment]
Hello, I tried to solve the issue.

This is what I did:

This change addresses the PHP warning about undefined array key 'lists' and null offset access. It modifies the condition to check if the 'lists' key exists in the options array and if it has a 'tasks' key before accessing it. This should resolve the warning while maintaining the existing functionality.

You can review changes in this commit: https://github.com/lattaai9/kuenzign-WikiMarkdown-19/commit/141ded2c52b02177cd003b4b9a840a61433035d9.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by fluchtkapsel** [comment]
Just for documentation purposes:

If ParsedownExtended has been installed using git as described in the installation instructions, downgrading is just a simple `git checkout v1.1.2` in the folder `extensions/ParsedownExtended`.
